# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  install-lint-test-build:
    environment:
      CC_TEST_REPORTER_ID: c8f294cd54feece3273291ddb744d3189db1d3eaa5cf10073e54e171fcd140ea
    docker:
      - image: cimg/node:14.1
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Install dependencies
          command: yarn lint
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run:
          name: Run all tests with coverage
          command: |
            yarn test:ci
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.frontend.json coverage/lcov.info
      - run:
          name: Generate build
          command: yarn build
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json

workflows:
  pipeline:
    jobs:
      - install-lint-test-build
